name       : python-rawkit
version    : 0.6.0
release    : 6
source     :
    - https://github.com/photoshell/rawkit/archive/v0.6.0.tar.gz : c07971ddbca9568cef93753ebb06a72b5b622f9b827a5d8bf96f2a137cc4219e
homepage   : https://github.com/photoshell/rawkit
license    : MIT
component  : programming.python
summary    : CTypes based LibRaw bindings
description: |
    rawkit (pronounced rocket) is a ctypes-based LibRaw binding for Python inspired by the Wand API.
builddeps  :
    - python-mock
    - python-pytest
rundeps    :
    - libraw
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
