name       : python-rawkit
version    : 0.6.0
release    : 2
source     :
    - https://github.com/photoshell/rawkit/archive/v0.6.0.tar.gz : c07971ddbca9568cef93753ebb06a72b5b622f9b827a5d8bf96f2a137cc4219e
license    : MIT
component  : programming.python
summary    : CTypes based LibRaw bindings
description: |
    rawkit (pronounced rocket) is a ctypes-based LibRaw binding for Python inspired by the Wand API.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - libraw
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
